### ISSUE TITLE
Object binding

### ISSUE THREAD

**Issue by francisco-ltech** [openai-php/client#277] opened 2023-11-27 15:05 UTC
### Description

Hi,

Is it possible to bind the response to a class?

E.g.: If I instruct a model to fetch specific information from a given content, e.g.; car name and car make. Is it possible to somehow do an automatic binding to a class containing those properties, e.g.: car_name and car_make? so that I don't have to fiddle with the extraction myself?

### Steps To Reproduce

N/A

### OpenAI PHP Client Version

N/A

### PHP Version

N/A

**Comment by gehrisandro** [comment] 2023-11-27 20:50
No there is no direct way for this. You may can reach for function calling or json response types.

Closing this as it is not a bug and not directly related to this package.

**Closed by gehrisandro** 2023-11-27 20:50 UTC
Labels: bug
