### ISSUE TITLE
($finishReason) must be of type string

### ISSUE THREAD

**Issue by diudiudiuu** [openai-php/client#54] opened 2023-02-28 06:27 UTC
local.ERROR: OpenAI\Responses\Completions\CreateResponseChoice::__construct(): Argument #4 ($finishReason) must be of type string, null given, called in /data1/chatgpt/vendor/openai-php/client/src/Responses/Completions/CreateResponseChoice.php on line 22 {"exception":"[object] (TypeError(code: 0): OpenAI\\Responses\\Completions\\CreateResponseChoice::__construct(): Argument #4 ($finishReason) must be of type string, null given, called in /data1/chatgpt/vendor/openai-php/client/src/Responses/Completions/CreateResponseChoice.php on line 22 at /data1/chatgpt/vendor/openai-php/client/src/Responses/Completions/CreateResponseChoice.php:9)
[stacktrace]

**Comment by anandmainali** [comment] 2023-02-28 06:35
yeah i'm having the same issue multiple times.

**Comment by careybaird** [comment] 2023-02-28 07:26
Duplicate of #50  (see this issue for a fix)

**Comment by diudiudiuu** [comment] 2023-02-28 08:29
> Duplicate of #50 (see this issue for a fix)

thank you

**Comment by nunomaduro** [comment] 2023-02-28 13:35
Fixed on `v0.3.2`.

**Closed by nunomaduro** 2023-02-28 13:35 UTC
